### ISSUE TITLE
How to upload files?

### ISSUE THREAD

**Issue by caracal7** [goriunov/ClusterWS#137]
Maybe somebody have example?

**Comment by goriunov** [comment]
@caracal7 ClusterWS is not responsible for uploading files, it should be done through http server (whichever you use, like express or koa or any other).

**Comment by caracal7** [comment]
But ClusterWS is also http server?

Maybe it's possible like in uWebsockets?
https://github.com/uNetworking/uWebSockets.js/blob/master/examples/Upload.js

**Comment by goriunov** [comment]
@caracal7  ClusterWS expose raw node js http/https request handler so that you can connect any http library such as express. For file uploader you can use something like https://www.npmjs.com/package/express-fileupload with express

Example: 
```js
function Worker() {
  ...
  const app = express();
  app.use(...); // use file upload here

  // any other express stuff
  // Connect ClusterWS and Express
  server.on('request', app);
  ...
}
```

uWebSockets example is working similar way but it uses more low level things like req, res streams where you have to join all chunks together and then parse your data.

If you want to do similar as uWebsockets in raw node js it would look something like:
```js
function Worker() {
  ...
   server.on('request', (request, response) => {
    // you can listen on data in request
     request.on("data", (chunk) => {
        // collect chunks and then you should be able to parse them
     })
   });
  ...
}
```

You can read more https://nodejs.org/es/docs/guides/anatomy-of-an-http-transaction/ 
just to get some idea how raw node js server works. Express, Kao and other libraries are just simplifying that logic. Especially read section `Request Body` as that is where your file data comes.

**Comment by caracal7** [comment]
Thanks a lot)
